# Generated by Django 4.2 on 2023-05-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterMidsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
