# Generated by Django 4.2 on 2023-05-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterMidsApp', '0002_rename_firstname_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
