# Generated by Django 4.2.1 on 2023-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment3App', '0002_training_task_payroll_meeting_expense_training_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
    ]
