# Generated by Django 3.2.12 on 2023-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_name', models.CharField(max_length=100)),
                ('head_name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('technologies', models.CharField(max_length=100)),
                ('universty_name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name=500)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phoneNo', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('id_no', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('vehicle_no', models.IntegerField()),
                ('expertise', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name=500)),
            ],
        ),
        migrations.CreateModel(
            name='se',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_name', models.CharField(max_length=100)),
                ('head_name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('technologies', models.CharField(max_length=100)),
                ('universty_name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name=500)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('id_no', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('universty_name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name=500)),
            ],
        ),
    ]
